language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
install:
  - npm install
before_script:
- npm install -save-dev cypress
- npm install -g httpserver
- npm run build
- cd dist && httpserver -p 8080 &
script:
  - npm run cypress
deploy:
  provider: surge
  skip_cleanup: true
  domain: dreammj.surge.sh
  project: ./dist
  on:
     branch: master